/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.chase22.derpibooru

import io.github.chase22.derpibooru.derpibooru.DerpibooruClient
import io.github.chase22.derpibooru.tag.Tag
import io.github.chase22.derpibooru.tag.TagMethod
import kotlin.test.Test

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val client: DerpibooruClient = DerpibooruClient()
        val tagMethod: TagMethod = TagMethod()
        val tag: List<Tag> = client.execute(tagMethod).get()
    }
}
